# Generated by Django 3.1.5 on 2021-01-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspark', '0002_bus_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='bus',
            field=models.ManyToManyField(to='buspark.Bus'),
        ),
    ]
