# Generated by Django 3.1.5 on 2021-01-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buspark', '0004_auto_20210117_2325'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bus',
            unique_together=set(),
        ),
    ]
